Fixes from proof-reading.
Pg 3/para 5: looks like the indexing commands on "globally" and "locally" didn't format correctly.

- Change intro.tex:150 and intro.tex:153 commands from \gref to \grefdex.

Pg 3/para 6: wording will be much clearer if we change "and of and not in" to "and of rather than in".

Pg 9/para 1: the statement "The keys do not have to be strings" is wrong - they _do_ have to be strings.  Please change to, "The keys have to be strings; the values can be anything."

Pg 10/para 4: "a parameterized list of parameters" is wrong: it should be "a parenthesized list".

Pg 10/para 5: replace the colon with a full stop and start a new sentence, so that it reads "...to the function. If values has no length..."

Pg 19: is it possible to move Figure 3.1 higher on the page so that it comes immediately after the first paragraph in Section 3.1 (i.e., immediately after the reference to the figure)? I think that will make the flow easier to follow.

Pg 20: similarly, is it possible to move Figure 3.3 down the page so that it appears immediately above the heading for Section 3.2 and is visually distanced from Figure 3.2? I think that will also make the flow easier to follow.

Pg 21: similarly, can we move Figure 3.5 down the page so that it appears immediately after the reference to it and before the paragraph beginning with "This becomes more useful..."?

Pg 22: There is an unnecessary line break after the reference to Figure 3.6 and before the sentence beginning, "Reversing the order..." Looking at the LaTeX source, this happened because Figure 3.6 was moved to the top of the page: if Figure 3.6 appears immediately after the reference to it, the problem will go away.

Pg 25/para 2: please change "and would politely, even patiently, suggest" to "and would politely but firmly suggest"

Pg 27/para 3: should "side-effect" be "side effect" (since 'side' is the adjective and 'effect' is the noun)?

Pg 30/last line: missing \noindent.

Pg 34/para 2: remove "also" so that the sentence reads "..., which turned out to be..."

Pg 36-37: is there any way to squeeze the first line from page 37 onto the bottom of page 36 to fix the widowed "}"?

Pg 39: there's a lot of unused space on this page - I think the top part of Pg 40 (which is the rest of the exercise started on page 38) can be put here.

Pg 45: there is also a lot of unused space on this page - I think it would make sense to move the list that begins at the bottom of page 44 and is continued on page 46 to this page.

Pg 51/last para: rather than "which is what we're using to style this website" it should read, "which is what we use to style our website", since this is the print edition rather than online.

Pg 67/para 2: something's gone wrong with "setTimeout@setTimeout"

- GVW: Changed "\texttt{setTimeout@\texttt{setTimeout}}" to "\index{setTimeout|texttt}" in pages.tex

Pg 67/exercise EXPLICITLY CREATING NODES: "[...] for the two function [...]" -> "[...] for the two functions [...]"

- GVW: made "function" plural in pages.tex

Pg 72/code chunk 1: weird box around closing h1 tag in "<h1>Hello JSX</h1>," - this is the first of many such boxes, which seem to coincide with the forward slashes in closing HTML tags, then run to the end of the line. As far as I can tell, the boxes are only present in the code examples using JSX - probably a product of the lack of quoting around HTML tags in code that is otherwise JavaScript. I guess the forward slashes interfere with Latex somehow? I'm afraid I've no expertise on this topic, so I'd be delighted if someone else can put their finger on exactly what's going wrong.

- GVW: after a bit of search I found an answer in this Stack Overflow question:  https://tex.stackexchange.com/questions/512254/is-there-a-way-to-properly-display-jsx-in-latex  We need to:

1. 'pip install jsx-lexer' to get a parser for JSX that the 'minted' package can use

2. change '\begin{minted}{html}' to '\begin{minted}{jsx}' wherever these weird boxes have shown up

I have made these changes in 'dynamic.tex' and it seems to solve the problem.

Pg 72/code chunk 2: same box problem (GVW fixed - please check)

Pg 73/code chunk 1: same box problem (GVW fixed - please check)

Pg 73/code chunk 2: same box problem (GVW fixed - please check)

Pg 76/code chunk 2: same box problem (GVW fixed - please check)

Pg 76/code chunk 3: same box problem (GVW fixed - please check)

Pg 77/code chunk 1: same box problem (GVW fixed - please check)

Pg 77/exercise THOSE DAMN CURLY BRACES: box around "/li> )}</ul>," in code chunk

- GVW fixed

Pg 88/para 4: another strange case of "setTimeout@setTimeout"

- changed to "\texttt{setTimeout}\index{setTimeout|texttt}" as above

Pg 92/code block 1: the URL in this code block is correct, which doesn't fit with the point about the error being caught (or not being caught, in fact) that we're trying to make in the text. Change date in URL to 2018-80-20

- GVW: and add a comment to highlight the change so that the two lines read

    url = 'https://api.nasa.gov/neo/rest/v1/feed' +
          '?api_key=DEMO_KEY&start_date=2018-80-20' // illegal date

Pg 93/para 2: change to "[...] process multiple files, for example to calculate their total size"

Pg 94/para 3: Change to "In future, we might also find an opportunity to use Promise.race, which [...]"

Pg 94/para 5: Change to "Before we begin, we will want the name of the directory to search for files."

Pg 103/code block 1: boxes around "/div>" and other closing HTML tags

- Here and below, the solution is to change "\begin{minted}{js}" to "\begin{minted}{jsx}" (i.e., 3-letter "jsx" instead of 2-letter "js") after installing the JSX parser as mentioned above. I've made the changes and pushed to github.com/software-tools-in-javascript/js4ds.

Pg 103/code block 2: same box problem

Pg 104/code block 1: same box problem

Pg 106/code block 1: same box problem

Pg 108/code block 1: same box problem

Pg 108/code block 2: same box problem

Pg 108/code block 4: same box problem

Pg 109/code block 1: same box problem

Pg 111/code block 1: same box problem

Pg 111/code block 2: same box problem

Pg 112/code block 2: same box problem

Pg 113/bullet point 2: change to "a function to call when the text box's value changes, and"

- GVW: i.e., insert "the"

Pg 114/code block 1: same box problem

Pg 121/para 2: change "We include an underscore to the start [...]" to "We include an underscore at the start [...]"

Pg 112/figure 12.2: "u" at end of bio.euphoric.edu has been cut off slightly

- GVW: confused by this one?

Pg 126/para 3: The opening parenthesis is never closed. Please remove the opening parenthesis

Pg 130/figure 12.3: arrow overlaps text in "web-dir/" box

- GVW: regenerated a new figure and committed to repository as figures/server-mapping.svg and figures/server-mapping.pdf

Pg 132/para 1: "[...] and a starting data, [...]" should read "[...] and a starting date, [...]"

Pg 133/para 2: "[...] to create the data the test's input" should read "[...] to create the data for the test's input [...]"

Pg 133/bullet points: these bullet points don't end with periods, which seems inconsistent with other lists throughout the book. Suggest to change to:

pass: everything worked,

fail:  the system being tested didn’t do what was expected, or

error: something went wrong with the test itself.

Pg 135/figure 13.1: text in the right-hand box overflows the border and seems to run off the side of the page itself

- GVW: new figure generated and committed to repo

Pg 156/Key Points: "[...] or by parse text [...]" -> "[...] or by parsing text [...]"

- GVW: it appears that a couple of points were lost here somehow - I have added them to keypoints/dataforge.tex and include them below.  This does not affect pagination.

```
\item
  If you're using a loop on a dataframe,
  you're doing the wrong thing.

\item
  Use method chaining to create pipelines
  that filter data and create new values from old.

\item
  Use grouping and aggregation to summarize data.
```

Pg 159/para 1: remove "piece" i.e. "[...] with at least one missing observation, [...]"

Pg 160/para 2: as we no longer see the filenames in the text (either online or in the book), the sentence "[...] we've called it driver-0, [...]" no longer makes sense. Suggest to change to "[...] we're referring to server-0, [...]"

Pg 164/para 2: change colon -> period at end of paragraph

Pg 165/code block 2: boxes again

- GVW: fixed by changing "\begin{minted}{js}" to "\begin{minted}{jsx}"

Pg 165/code block 3: same box problem

- GVW: fixed by changing "\begin{minted}{js}" to "\begin{minted}{jsx}"

Pg 165/para 2: change beginning to "We will display survey statistics [...]"

Pg 166/code block 1: same box problem

- GVW: fixed as above

Pg 166/code block 2: same box problem

- GVW: fixed as above

Pg 167/code block 1: same box problem

- GVW: fixed as above

Page 187: "model (of data)" should end with "See also view" - problem is use of \gitem instead of \grefcross - fixed.

Page 189 definition of parent node: "the" should be capitalized "The" for consistency. Fixed and committed.

Page 192 "view (of data)" should end with "See also model" - same problem as above, fixed the same way.

Page 210/p4 the same red box from Toby’s comments around "\" in the code sample; fixed by removing "\n".